services:
  postgres:
    ports:
      - '54332:5432'
    image: postgis/postgis:16-3.4-alpine
    environment:
      TZ: Asia/Tashkent
      PGTZ: Asia/Tashkent
      POSTGRES_DB: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'